[[redirects]]
    from = "/git/*"
    to = "https://ari-web.xyz/gh/user.ari-web.xyz/:splat"
    force = true
    status = 301

[[redirects]]
    from = "/favicon.ico"
    to = "https://ari-web.xyz/favicon.ico"
    status = 200
    force = true

[[redirects]]
    from = "/*"
    to = "https://ari-web.xyz/404.comment.xyz"
    status = 404
    force = false

[[headers]]
    for = "/*"

    [headers.values]
        Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
        X-Frame-Options = "deny"
        X-Content-Type-Options = "nosniff"
        Content-Security-Policy = "upgrade-insecure-requests"
        X-Permitted-Cross-Domain-Policies = "none"
        Referrer-Policy = "no-referrer"
