# see netlify.toml.old for configuration pre-ari.lt

[[redirects]]
    from = "/*"
    to = "https://us.ari.lt/:splat"
    force = true
    status = 301

[[headers]]
    for = "/content/js/linkify.js"

    [headers.values]
        Access-Control-Allow-Origin = "ari.lt"
        Access-Control-Allow-Methods = "GET"

[[headers]]
    for = "/*"

    [headers.values]
        Strict-Transport-Security = "max-age=0"
        X-Frame-Options = "deny"
        X-Content-Type-Options = "nosniff"
        Content-Security-Policy = "upgrade-insecure-requests"
        X-Permitted-Cross-Domain-Policies = "none"
        Referrer-Policy = "no-referrer"
